app/__init__.py
from flask import Flask
from dotenv import load_dotenv
import os

from .apis import api_bp
from .routes import route_bp
from .extensions import mongo

def create_app():

    load_dotenv()

    app = Flask(__name__)
    app.debug = True

    #mongodb configuration
    app.config['MONGO_URI'] = f"mongodb+srv://{os.environ.get('MONGO_USER')}:{os.environ.get('MONGO_PASS')}@cluster0.aoytkvo.mongodb.net/fastfood?retryWrites=true&w=majority"

    mongo.init_app(app)

    app.register_blueprint(route_bp)
    app.register_blueprint(api_bp, url_prefix='/api')

    return app

if __name__ == '__main__':
    app = create_app()
   

app/apis/__init__.py
from flask import Blueprint

api_bp = Blueprint('api', __name__)

from .foods import foods_bp

api_bp.register_blueprint(foods_bp)

app/routes.py
from flask import Blueprint, render_template

route_bp = Blueprint('route_bp', __name__)

@route_bp.route('/')
def home():
    return render_template('pages/index.html')

@route_bp.route('/about')
def about():
    return render_template('pages/about.html')

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Flask App</title>
    <!-- Include Tailwind CSS from CDN -->
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
</head>
<body class="bg-gray-100">
    <header>
        <header>
            <h1>My Simple Flask Application</h1>
            <nav>
                <ul>
                    <li><a href="{{ url_for('route_bp.home') }}">Home</a></li>
                </ul>
            </nav>
        </header>
    </header>
    <main>
        {% block content %}{% endblock %}
    </main>
    <footer>
        <p>&copy; {{ year }} My Simple Flask Application. All rights reserved.</p>
    </footer>
</body>
</html>

app/templates/components/footer.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Footer</h1>
{% endblock %}

app/templates/components/header.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Header</h1>
{% endblock %}

app/templates/pages/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock %}

{% block content %}
    <h1>About Page</h1>
    
{% endblock %}

app/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <h1>Welcome to My Flask App</h1>
    <p>This is the home page.</p>
{% endblock %}